name: Package-Debian-Build

on:
  push:
    tags:
      - '*'

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  Debian:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.distro }}
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        distro: [focal, jammy, noble]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: target_ws/src

      - name: Build and test
        uses: tesseract-robotics/colcon-action@v9
        with:
          ccache-enabled: false
          add-ros-ppa: true
          rosdep-enabled: true
          target-path: target_ws/src
          target-args: --cmake-args -DCMAKE_BUILD_TYPE=Release -DIFOPT_PACKAGE=ON
          run-tests: false

      - name: Create artifacts directory
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts

      - name: Package
        working-directory: target_ws/build/ifopt
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: debian_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.deb

      - uses: actions/upload-artifact@v4
        with:
          name: archive_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.tar.xz
